Repository exasol/row-level-security, pull requests merged in 2020-01, with the labels that each got.

#33 #11: updated exasol-test-containers version and removed timers from t…
  .travis.yml
  doc/user_guide/user_guide.md
  pom.xml
  src/test/java/com/exasol/adapter/dialects/rls/RowLevelSecurityDialectIT.java
  src/test/java/com/exasol/matcher/ResultSetMatcher.java
Labels: refactoring

#35 #30: Improved connection option documentation.
  doc/user_guide/user_guide.md
Labels: documentation

#37 36: Pack each admin script into bundle only once
  doc/user_guide/user_guide.md
  pom.xml
  src/test/java/com/exasol/adapter/dialects/rls/RowLevelSecurityDialectIT.java
  tools/assemble_sql_scripts.sh
Labels: bug
