Repository exasol/row-level-security, pull requests merged in 2020-11, with the labels that each got.

#68 * #67: Updated to the latest version of Exasol dialect containing a s…
  .github/workflows/github_release.yml
  .github/workflows/maven.yml
  doc/changes/changelog.md
  doc/changes/changes_1.2.1.md
  doc/user_guide/tutorial.md
  doc/user_guide/user_guide.md
  pom.xml
  src/main/java/com/exasol/adapter/dialects/rls/RowLevelSecurityQueryRewriter.java
  src/test/java/com/exasol/adapter/dialects/rls/AbstractRowLevelSecurityIT.java
  src/test/java/com/exasol/tools/TestsConstants.java
  versionsMavenPluginRules.xml
Labels: refactoring

#69 #6: Password is exposed in EXPLAIN VIRTUAL for non local EXA connections
  doc/changes/changelog.md
  doc/changes/changes_2.0.0.md
  doc/user_guide/user_guide.md
  pom.xml
  src/test/java/com/exasol/adapter/dialects/rls/AbstractRowLevelSecurityIT.java
  src/test/java/com/exasol/adapter/dialects/rls/RowLevelSecurityExaConnectionIT.java
  src/test/java/com/exasol/adapter/dialects/rls/RowLevelSecurityJdbcIT.java
  src/test/java/com/exasol/adapter/dialects/rls/RowLevelSecurityLocalExaConnectionIT.java
  src/test/java/com/exasol/adapter/dialects/rls/RowLevelSecurityLocalIT.java
  src/test/java/com/exasol/rls/administration/scripts/AddRlsRoleIT.java
  src/test/java/com/exasol/rls/administration/scripts/AddUserToGroupIT.java
  src/test/java/com/exasol/rls/administration/scripts/AssignRolesToUserIT.java
  src/test/java/com/exasol/rls/administration/scripts/DeleteRlsRoleIT.java
  src/test/java/com/exasol/rls/administration/scripts/ListAllGroupsIT.java
  src/test/java/com/exasol/rls/administration/scripts/ListUserGroupsIT.java
  src/test/java/com/exasol/rls/administration/scripts/RemoveUserFromGroupIT.java
  src/test/java/com/exasol/rls/administration/scripts/RolesMaskIT.java
  src/test/java/com/exasol/tools/TestsConstants.java
Labels: bug

#72 #70: Use `project-keeper`
  .github/workflows/dependencies_check.yml
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  .travis.yml
  README.md
  doc/changes/changes_2.0.0.md
  doc/user_guide/tutorial.md
  doc/user_guide/user_guide.md
  pom.xml
  src/assembly/all-dependencies.xml
  src/test/java/com/exasol/tools/TestsConstants.java
  versionsMavenPluginRules.xml
Labels: refactoring

#74 #73: Add missing dependency in README
  README.md
  doc/changes/changelog.md
  doc/changes/changes_2.0.1.md
Labels: documentation
